---
- hosts: all
  become: yes

  tasks:
   - name: Install docker packages
     apt:
       name: ['apt-transport-https','ca-certificates', 'curl', 'software-properties-common']
       state: present
       update_cache: yes
     tags:
       - docker

   - name: Add Docker s GPG key for ubuntu from official site
     apt_key:
       url: https://download.docker.com/linux/ubuntu/gpg
       state: present
     tags:
       - docker

   - name: Configure Docker for ubuntu stable repository
     apt_repository:
       repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
       state: present
       update_cache: yes
     tags:
        - docker

   - name: Install docker-ce
     apt:
       name: docker-ce
       state: present
       update_cache: yes
     tags:
        - docker

   - name: Add user to "docker" group
     user:
       name: ubuntu
       groups: "docker"
       append: yes
     tags:
        - docker

   - name: Install docker-compose from official github repo
     get_url:
       url : https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
       dest: /usr/local/bin/docker-compose
       mode: 'u+x,g+x'
